services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    restart: unless-stopped
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  nexus:
    image: sonatype/nexus3:latest
    ports:
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data

volumes:
  my-db:
    driver: local